// GENERATED by `supabase gen types typescript` from the live schema
// (project xkghxfrseybawpxxvjvv). Do not edit by hand; run `npm run gen:types`.
//
// The app's stricter, hand-written aliases live in database.ts. The two are
// held in step at compile time by database.check.ts.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      budgets: {
        Row: {
          category: Database["public"]["Enums"]["item_category"]
          created_at: string
          id: string
          max_cents: number
          min_cents: number
          profile_id: string
          updated_at: string
        }
        Insert: {
          category: Database["public"]["Enums"]["item_category"]
          created_at?: string
          id?: string
          max_cents: number
          min_cents?: number
          profile_id: string
          updated_at?: string
        }
        Update: {
          category?: Database["public"]["Enums"]["item_category"]
          created_at?: string
          id?: string
          max_cents?: number
          min_cents?: number
          profile_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "budgets_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      closet_members: {
        Row: {
          accepted_at: string | null
          closet_id: string
          created_at: string
          id: string
          invited_by: string | null
          role: Database["public"]["Enums"]["closet_role"]
          status: Database["public"]["Enums"]["member_status"]
          updated_at: string
          user_id: string
        }
        Insert: {
          accepted_at?: string | null
          closet_id: string
          created_at?: string
          id?: string
          invited_by?: string | null
          role: Database["public"]["Enums"]["closet_role"]
          status?: Database["public"]["Enums"]["member_status"]
          updated_at?: string
          user_id: string
        }
        Update: {
          accepted_at?: string | null
          closet_id?: string
          created_at?: string
          id?: string
          invited_by?: string | null
          role?: Database["public"]["Enums"]["closet_role"]
          status?: Database["public"]["Enums"]["member_status"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "closet_members_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "closet_members_invited_by_fkey"
            columns: ["invited_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "closet_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      closets: {
        Row: {
          created_at: string
          id: string
          name: string
          owner_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name?: string
          owner_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          owner_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "closets_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      inspiration_looks: {
        Row: {
          analysis_error: string | null
          closet_id: string
          created_at: string
          created_by: string
          id: string
          note: string | null
          saved_outfit_id: string | null
          status: Database["public"]["Enums"]["look_status"]
          storage_path: string
          thumb_path: string
          title: string | null
          updated_at: string
        }
        Insert: {
          analysis_error?: string | null
          closet_id: string
          created_at?: string
          created_by: string
          id?: string
          note?: string | null
          saved_outfit_id?: string | null
          status?: Database["public"]["Enums"]["look_status"]
          storage_path: string
          thumb_path: string
          title?: string | null
          updated_at?: string
        }
        Update: {
          analysis_error?: string | null
          closet_id?: string
          created_at?: string
          created_by?: string
          id?: string
          note?: string | null
          saved_outfit_id?: string | null
          status?: Database["public"]["Enums"]["look_status"]
          storage_path?: string
          thumb_path?: string
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "inspiration_looks_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inspiration_looks_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inspiration_looks_saved_outfit_id_fkey"
            columns: ["saved_outfit_id"]
            isOneToOne: false
            referencedRelation: "outfits"
            referencedColumns: ["id"]
          },
        ]
      }
      inspiration_pieces: {
        Row: {
          category: Database["public"]["Enums"]["item_category"] | null
          closet_id: string
          colors: string[]
          confidence: number | null
          created_at: string
          description: string
          id: string
          look_id: string
          match_status: Database["public"]["Enums"]["piece_match"]
          matched_item_id: string | null
          position: number
        }
        Insert: {
          category?: Database["public"]["Enums"]["item_category"] | null
          closet_id: string
          colors?: string[]
          confidence?: number | null
          created_at?: string
          description: string
          id?: string
          look_id: string
          match_status?: Database["public"]["Enums"]["piece_match"]
          matched_item_id?: string | null
          position?: number
        }
        Update: {
          category?: Database["public"]["Enums"]["item_category"] | null
          closet_id?: string
          colors?: string[]
          confidence?: number | null
          created_at?: string
          description?: string
          id?: string
          look_id?: string
          match_status?: Database["public"]["Enums"]["piece_match"]
          matched_item_id?: string | null
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "inspiration_pieces_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inspiration_pieces_look_id_fkey"
            columns: ["look_id"]
            isOneToOne: false
            referencedRelation: "inspiration_looks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inspiration_pieces_matched_item_id_fkey"
            columns: ["matched_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      invites: {
        Row: {
          closet_id: string
          code_hash: string
          code_hint: string
          created_at: string
          created_by: string
          expires_at: string
          id: string
          redeemed_at: string | null
          redeemed_by: string | null
          revoked_at: string | null
          role: Database["public"]["Enums"]["closet_role"]
        }
        Insert: {
          closet_id: string
          code_hash: string
          code_hint: string
          created_at?: string
          created_by: string
          expires_at: string
          id?: string
          redeemed_at?: string | null
          redeemed_by?: string | null
          revoked_at?: string | null
          role?: Database["public"]["Enums"]["closet_role"]
        }
        Update: {
          closet_id?: string
          code_hash?: string
          code_hint?: string
          created_at?: string
          created_by?: string
          expires_at?: string
          id?: string
          redeemed_at?: string | null
          redeemed_by?: string | null
          revoked_at?: string | null
          role?: Database["public"]["Enums"]["closet_role"]
        }
        Relationships: [
          {
            foreignKeyName: "invites_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invites_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "invites_redeemed_by_fkey"
            columns: ["redeemed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      item_photos: {
        Row: {
          bytes: number | null
          closet_id: string
          created_at: string
          height: number | null
          id: string
          item_id: string
          position: number
          storage_path: string
          thumb_path: string
          width: number | null
        }
        Insert: {
          bytes?: number | null
          closet_id: string
          created_at?: string
          height?: number | null
          id?: string
          item_id: string
          position?: number
          storage_path: string
          thumb_path: string
          width?: number | null
        }
        Update: {
          bytes?: number | null
          closet_id?: string
          created_at?: string
          height?: number | null
          id?: string
          item_id?: string
          position?: number
          storage_path?: string
          thumb_path?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "item_photos_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "item_photos_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
      items: {
        Row: {
          ai_confidence: number | null
          ai_raw: Json | null
          barcode: string | null
          brand: string | null
          category: Database["public"]["Enums"]["item_category"]
          closet_id: string
          colors: string[]
          created_at: string
          created_by: string
          formality: number
          id: string
          is_dirty: boolean
          is_favorite: boolean
          last_worn_at: string | null
          material: string | null
          name: string
          notes: string | null
          pattern: string | null
          primary_photo_id: string | null
          purchase_price_cents: number | null
          seasons: Database["public"]["Enums"]["season"][]
          size: string | null
          source: Database["public"]["Enums"]["item_source"]
          status: Database["public"]["Enums"]["item_status"]
          style_number: string | null
          subcategory: string | null
          tags: string[]
          updated_at: string
          wear_count: number
        }
        Insert: {
          ai_confidence?: number | null
          ai_raw?: Json | null
          barcode?: string | null
          brand?: string | null
          category: Database["public"]["Enums"]["item_category"]
          closet_id: string
          colors?: string[]
          created_at?: string
          created_by: string
          formality?: number
          id?: string
          is_dirty?: boolean
          is_favorite?: boolean
          last_worn_at?: string | null
          material?: string | null
          name: string
          notes?: string | null
          pattern?: string | null
          primary_photo_id?: string | null
          purchase_price_cents?: number | null
          seasons?: Database["public"]["Enums"]["season"][]
          size?: string | null
          source?: Database["public"]["Enums"]["item_source"]
          status?: Database["public"]["Enums"]["item_status"]
          style_number?: string | null
          subcategory?: string | null
          tags?: string[]
          updated_at?: string
          wear_count?: number
        }
        Update: {
          ai_confidence?: number | null
          ai_raw?: Json | null
          barcode?: string | null
          brand?: string | null
          category?: Database["public"]["Enums"]["item_category"]
          closet_id?: string
          colors?: string[]
          created_at?: string
          created_by?: string
          formality?: number
          id?: string
          is_dirty?: boolean
          is_favorite?: boolean
          last_worn_at?: string | null
          material?: string | null
          name?: string
          notes?: string | null
          pattern?: string | null
          primary_photo_id?: string | null
          purchase_price_cents?: number | null
          seasons?: Database["public"]["Enums"]["season"][]
          size?: string | null
          source?: Database["public"]["Enums"]["item_source"]
          status?: Database["public"]["Enums"]["item_status"]
          style_number?: string | null
          subcategory?: string | null
          tags?: string[]
          updated_at?: string
          wear_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "items_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "items_primary_photo_fk"
            columns: ["primary_photo_id"]
            isOneToOne: false
            referencedRelation: "item_photos"
            referencedColumns: ["id"]
          },
        ]
      }
      message_attachments: {
        Row: {
          closet_id: string
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["attachment_kind"]
          message_id: string
          ref_id: string | null
          storage_path: string | null
          thumb_path: string | null
        }
        Insert: {
          closet_id: string
          created_at?: string
          id?: string
          kind: Database["public"]["Enums"]["attachment_kind"]
          message_id: string
          ref_id?: string | null
          storage_path?: string | null
          thumb_path?: string | null
        }
        Update: {
          closet_id?: string
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["attachment_kind"]
          message_id?: string
          ref_id?: string | null
          storage_path?: string | null
          thumb_path?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "message_attachments_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "message_attachments_message_id_fkey"
            columns: ["message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string | null
          closet_id: string
          created_at: string
          edited_at: string | null
          id: string
          sender_id: string
        }
        Insert: {
          body?: string | null
          closet_id: string
          created_at?: string
          edited_at?: string | null
          id?: string
          sender_id: string
        }
        Update: {
          body?: string | null
          closet_id?: string
          created_at?: string
          edited_at?: string | null
          id?: string
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      outfit_feedback: {
        Row: {
          author_id: string
          closet_id: string
          created_at: string
          id: string
          note: string | null
          outfit_id: string
          verdict: Database["public"]["Enums"]["feedback_verdict"]
        }
        Insert: {
          author_id: string
          closet_id: string
          created_at?: string
          id?: string
          note?: string | null
          outfit_id: string
          verdict: Database["public"]["Enums"]["feedback_verdict"]
        }
        Update: {
          author_id?: string
          closet_id?: string
          created_at?: string
          id?: string
          note?: string | null
          outfit_id?: string
          verdict?: Database["public"]["Enums"]["feedback_verdict"]
        }
        Relationships: [
          {
            foreignKeyName: "outfit_feedback_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outfit_feedback_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outfit_feedback_outfit_id_fkey"
            columns: ["outfit_id"]
            isOneToOne: false
            referencedRelation: "outfits"
            referencedColumns: ["id"]
          },
        ]
      }
      outfit_items: {
        Row: {
          closet_id: string
          created_at: string
          item_id: string
          outfit_id: string
          position: number
          slot: Database["public"]["Enums"]["item_category"]
        }
        Insert: {
          closet_id: string
          created_at?: string
          item_id: string
          outfit_id: string
          position?: number
          slot: Database["public"]["Enums"]["item_category"]
        }
        Update: {
          closet_id?: string
          created_at?: string
          item_id?: string
          outfit_id?: string
          position?: number
          slot?: Database["public"]["Enums"]["item_category"]
        }
        Relationships: [
          {
            foreignKeyName: "outfit_items_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outfit_items_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outfit_items_outfit_id_fkey"
            columns: ["outfit_id"]
            isOneToOne: false
            referencedRelation: "outfits"
            referencedColumns: ["id"]
          },
        ]
      }
      outfits: {
        Row: {
          closet_id: string
          created_at: string
          created_by: string
          flagged_for_review: boolean
          generated_for: string | null
          id: string
          name: string | null
          note: string | null
          occasion: string | null
          reason: string | null
          source: Database["public"]["Enums"]["outfit_source"]
          status: Database["public"]["Enums"]["outfit_status"]
          temp_c: number | null
          updated_at: string
          weather_summary: string | null
          worn_at: string | null
        }
        Insert: {
          closet_id: string
          created_at?: string
          created_by: string
          flagged_for_review?: boolean
          generated_for?: string | null
          id?: string
          name?: string | null
          note?: string | null
          occasion?: string | null
          reason?: string | null
          source: Database["public"]["Enums"]["outfit_source"]
          status?: Database["public"]["Enums"]["outfit_status"]
          temp_c?: number | null
          updated_at?: string
          weather_summary?: string | null
          worn_at?: string | null
        }
        Update: {
          closet_id?: string
          created_at?: string
          created_by?: string
          flagged_for_review?: boolean
          generated_for?: string | null
          id?: string
          name?: string | null
          note?: string | null
          occasion?: string | null
          reason?: string | null
          source?: Database["public"]["Enums"]["outfit_source"]
          status?: Database["public"]["Enums"]["outfit_status"]
          temp_c?: number | null
          updated_at?: string
          weather_summary?: string | null
          worn_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "outfits_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "outfits_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      product_lookup_cache: {
        Row: {
          barcode: string
          fetched_at: string
          found: boolean
          hit_count: number
          payload: Json | null
          provider: string
        }
        Insert: {
          barcode: string
          fetched_at?: string
          found: boolean
          hit_count?: number
          payload?: Json | null
          provider: string
        }
        Update: {
          barcode?: string
          fetched_at?: string
          found?: boolean
          hit_count?: number
          payload?: Json | null
          provider?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_path: string | null
          created_at: string
          display_name: string | null
          home_lat: number | null
          home_lon: number | null
          id: string
          jacket_size: string | null
          monthly_budget_cents: number | null
          onboarded_at: string | null
          pants_length: number | null
          pants_waist: number | null
          shirt_size: string | null
          shoe_size: number | null
          updated_at: string
        }
        Insert: {
          avatar_path?: string | null
          created_at?: string
          display_name?: string | null
          home_lat?: number | null
          home_lon?: number | null
          id: string
          jacket_size?: string | null
          monthly_budget_cents?: number | null
          onboarded_at?: string | null
          pants_length?: number | null
          pants_waist?: number | null
          shirt_size?: string | null
          shoe_size?: number | null
          updated_at?: string
        }
        Update: {
          avatar_path?: string | null
          created_at?: string
          display_name?: string | null
          home_lat?: number | null
          home_lon?: number | null
          id?: string
          jacket_size?: string | null
          monthly_budget_cents?: number | null
          onboarded_at?: string | null
          pants_length?: number | null
          pants_waist?: number | null
          shirt_size?: string | null
          shoe_size?: number | null
          updated_at?: string
        }
        Relationships: []
      }
      push_tokens: {
        Row: {
          created_at: string
          device_name: string | null
          id: string
          last_seen_at: string
          platform: string
          token: string
          user_id: string
        }
        Insert: {
          created_at?: string
          device_name?: string | null
          id?: string
          last_seen_at?: string
          platform?: string
          token: string
          user_id: string
        }
        Update: {
          created_at?: string
          device_name?: string | null
          id?: string
          last_seen_at?: string
          platform?: string
          token?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "push_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      shopping_options: {
        Row: {
          checked_at: string
          chosen_by: string | null
          closet_id: string
          created_at: string
          id: string
          image_url: string | null
          local_store: boolean
          note: string | null
          over_budget: boolean
          piece_id: string | null
          price_cents: number | null
          store_name: string | null
          tier: Database["public"]["Enums"]["price_tier"]
          title: string
          url: string | null
        }
        Insert: {
          checked_at?: string
          chosen_by?: string | null
          closet_id: string
          created_at?: string
          id?: string
          image_url?: string | null
          local_store?: boolean
          note?: string | null
          over_budget?: boolean
          piece_id?: string | null
          price_cents?: number | null
          store_name?: string | null
          tier?: Database["public"]["Enums"]["price_tier"]
          title: string
          url?: string | null
        }
        Update: {
          checked_at?: string
          chosen_by?: string | null
          closet_id?: string
          created_at?: string
          id?: string
          image_url?: string | null
          local_store?: boolean
          note?: string | null
          over_budget?: boolean
          piece_id?: string | null
          price_cents?: number | null
          store_name?: string | null
          tier?: Database["public"]["Enums"]["price_tier"]
          title?: string
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "shopping_options_chosen_by_fkey"
            columns: ["chosen_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shopping_options_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "shopping_options_piece_id_fkey"
            columns: ["piece_id"]
            isOneToOne: false
            referencedRelation: "inspiration_pieces"
            referencedColumns: ["id"]
          },
        ]
      }
      style_rules: {
        Row: {
          author_id: string
          closet_id: string
          created_at: string
          id: string
          is_active: boolean
          machine_rule: Json | null
          rule_text: string
          strength: Database["public"]["Enums"]["rule_strength"]
          updated_at: string
        }
        Insert: {
          author_id: string
          closet_id: string
          created_at?: string
          id?: string
          is_active?: boolean
          machine_rule?: Json | null
          rule_text: string
          strength?: Database["public"]["Enums"]["rule_strength"]
          updated_at?: string
        }
        Update: {
          author_id?: string
          closet_id?: string
          created_at?: string
          id?: string
          is_active?: boolean
          machine_rule?: Json | null
          rule_text?: string
          strength?: Database["public"]["Enums"]["rule_strength"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "style_rules_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "style_rules_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
        ]
      }
      wear_log: {
        Row: {
          closet_id: string
          created_at: string
          id: string
          item_id: string
          outfit_id: string | null
          worn_on: string
        }
        Insert: {
          closet_id: string
          created_at?: string
          id?: string
          item_id: string
          outfit_id?: string | null
          worn_on?: string
        }
        Update: {
          closet_id?: string
          created_at?: string
          id?: string
          item_id?: string
          outfit_id?: string | null
          worn_on?: string
        }
        Relationships: [
          {
            foreignKeyName: "wear_log_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wear_log_item_id_fkey"
            columns: ["item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wear_log_outfit_fk"
            columns: ["outfit_id"]
            isOneToOne: false
            referencedRelation: "outfits"
            referencedColumns: ["id"]
          },
        ]
      }
      wishlist_items: {
        Row: {
          barcode: string | null
          brand: string | null
          category: Database["public"]["Enums"]["item_category"] | null
          closet_id: string
          colors: string[]
          created_at: string
          created_by: string
          fit_summary: string | null
          id: string
          image_path: string | null
          image_url: string | null
          name: string
          note: string | null
          over_budget: boolean
          pairs_with: string[]
          price_cents: number | null
          purchased_item_id: string | null
          recommended_by: string | null
          similar_item_id: string | null
          size: string | null
          source: Database["public"]["Enums"]["wishlist_source"]
          status: Database["public"]["Enums"]["wishlist_status"]
          store_name: string | null
          style_number: string | null
          updated_at: string
          url: string | null
        }
        Insert: {
          barcode?: string | null
          brand?: string | null
          category?: Database["public"]["Enums"]["item_category"] | null
          closet_id: string
          colors?: string[]
          created_at?: string
          created_by: string
          fit_summary?: string | null
          id?: string
          image_path?: string | null
          image_url?: string | null
          name: string
          note?: string | null
          over_budget?: boolean
          pairs_with?: string[]
          price_cents?: number | null
          purchased_item_id?: string | null
          recommended_by?: string | null
          similar_item_id?: string | null
          size?: string | null
          source?: Database["public"]["Enums"]["wishlist_source"]
          status?: Database["public"]["Enums"]["wishlist_status"]
          store_name?: string | null
          style_number?: string | null
          updated_at?: string
          url?: string | null
        }
        Update: {
          barcode?: string | null
          brand?: string | null
          category?: Database["public"]["Enums"]["item_category"] | null
          closet_id?: string
          colors?: string[]
          created_at?: string
          created_by?: string
          fit_summary?: string | null
          id?: string
          image_path?: string | null
          image_url?: string | null
          name?: string
          note?: string | null
          over_budget?: boolean
          pairs_with?: string[]
          price_cents?: number | null
          purchased_item_id?: string | null
          recommended_by?: string | null
          similar_item_id?: string | null
          size?: string | null
          source?: Database["public"]["Enums"]["wishlist_source"]
          status?: Database["public"]["Enums"]["wishlist_status"]
          store_name?: string | null
          style_number?: string | null
          updated_at?: string
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "wishlist_items_closet_id_fkey"
            columns: ["closet_id"]
            isOneToOne: false
            referencedRelation: "closets"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wishlist_items_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wishlist_items_purchased_item_id_fkey"
            columns: ["purchased_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wishlist_items_recommended_by_fkey"
            columns: ["recommended_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "wishlist_items_similar_item_id_fkey"
            columns: ["similar_item_id"]
            isOneToOne: false
            referencedRelation: "items"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      create_invite: {
        Args: { p_closet: string; p_ttl?: string }
        Returns: {
          code: string
          expires_at: string
          invite_id: string
        }[]
      }
      gen_invite_code: { Args: never; Returns: string }
      hash_invite_code: { Args: { p_code: string }; Returns: string }
      is_closet_member: { Args: { p_closet: string }; Returns: boolean }
      is_closet_owner: { Args: { p_closet: string }; Returns: boolean }
      redeem_invite: {
        Args: { p_code: string }
        Returns: {
          closet_id: string
          closet_name: string
          owner_name: string
          status: string
        }[]
      }
      safe_uuid: { Args: { p_text: string }; Returns: string }
    }
    Enums: {
      attachment_kind: "item" | "outfit" | "wishlist" | "inspiration" | "photo"
      closet_role: "owner" | "stylist"
      feedback_verdict: "approved" | "rejected" | "edited" | "comment"
      item_category: "top" | "bottom" | "outerwear" | "shoes" | "accessory"
      item_source: "manual" | "ai_single" | "ai_rack" | "scan"
      item_status: "active" | "donated"
      look_status: "pending" | "analyzing" | "analyzed" | "failed" | "saved"
      member_status: "pending" | "accepted" | "revoked"
      outfit_source: "ai" | "stylist" | "owner"
      outfit_status: "suggested" | "saved" | "worn" | "archived"
      piece_match: "have" | "close" | "missing"
      price_tier: "budget" | "mid" | "premium"
      rule_strength: "hard" | "soft"
      season: "spring" | "summer" | "fall" | "winter"
      wishlist_source: "owner" | "stylist" | "ai" | "inspiration"
      wishlist_status: "open" | "purchased" | "dismissed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      attachment_kind: ["item", "outfit", "wishlist", "inspiration", "photo"],
      closet_role: ["owner", "stylist"],
      feedback_verdict: ["approved", "rejected", "edited", "comment"],
      item_category: ["top", "bottom", "outerwear", "shoes", "accessory"],
      item_source: ["manual", "ai_single", "ai_rack", "scan"],
      item_status: ["active", "donated"],
      look_status: ["pending", "analyzing", "analyzed", "failed", "saved"],
      member_status: ["pending", "accepted", "revoked"],
      outfit_source: ["ai", "stylist", "owner"],
      outfit_status: ["suggested", "saved", "worn", "archived"],
      piece_match: ["have", "close", "missing"],
      price_tier: ["budget", "mid", "premium"],
      rule_strength: ["hard", "soft"],
      season: ["spring", "summer", "fall", "winter"],
      wishlist_source: ["owner", "stylist", "ai", "inspiration"],
      wishlist_status: ["open", "purchased", "dismissed"],
    },
  },
} as const
